from django.urls import path
from AppAdmin.api.api import (
    Registration,
    login,
    change_password,
    Admin_Dashboard,
    lists,
    user_edit_data,
    user_detail,
    executivelists,
    location_list,
    upload_file,
    daily_summary,
    admin_collection_list,
    supply_report_list,
    admin_collection_data,
    netsales,
    get_plant_edition,
    ProfileSettingView,
    ProfileSave,
    Notifications_web,
    NotificationsFCMHTTP,
)

urlpatterns = [
    path('registration/', Registration, name='registration'),
    # path('login/', login, name='login'),
    path('change-password/', change_password, name='change_password'),
    path('admin-dashboard/', Admin_Dashboard, name='admin_dashboard'),
    path('lists/', lists, name='lists'),
    path('user-edit-data/', user_edit_data, name='user_edit_data'),
    path('user-detail/', user_detail, name='user_detail'),
    path('executive-lists/', executivelists, name='executive_lists'),
    path('location-list/', location_list, name='location_list'),
    path('upload/', upload_file, name='upload_file'),
    path('daily-summary/', daily_summary, name='daily_summary'),
    path('payment-collection-list/', admin_collection_list, name='admin_collection_list'),
    path('supply-report-list/', supply_report_list, name='supply_report_list'),
    path('admin-collection-data/', admin_collection_data, name='admin_collection_data'),
    path('netsales/', netsales, name='netsales'),
    path('plant-edition/', get_plant_edition, name='plant_edition'),
    path('profile-setting/', ProfileSettingView, name='profile_setting'),
    path('profile-save/', ProfileSave, name='profile_save'),
    path('notifications/', Notifications_web, name='notifications_web'),
    path('notifications-fcm/', NotificationsFCMHTTP, name='notifications_fcm'),
    path('change-password/', change_password, name="change_password")
]
