# Generated by Django 5.0.7 on 2024-08-04 07:23

import App.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCollectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=100)),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=10)),
                ('bill_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_adjustment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_collected', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_dues', models.DecimalField(decimal_places=2, max_digits=10)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('executive', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NetSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manager', models.CharField(max_length=255)),
                ('AgentName', models.CharField(max_length=100)),
                ('Territory', models.TextField()),
                ('DropPoint', models.TextField()),
                ('Total_net_sales', models.IntegerField()),
                ('Executive', models.CharField(max_length=100)),
                ('Publication', models.CharField(choices=[('DH', 'dh'), ('PV', 'pv'), ('Mayura', 'mayura')], max_length=255)),
                ('Date', models.DateField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_time', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=250)),
                ('content', models.TextField()),
                ('notification_image', models.ImageField(blank=True, null=True, upload_to='notifications/')),
                ('role', models.CharField(choices=[('all users', 'All Users'), ('superadmin', 'Super Admin'), ('executive', 'Executive'), ('agent', 'Agents')], max_length=100)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('pending', 'Pending')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SupplyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SEname', models.CharField(max_length=255)),
                ('BPcode', models.BigIntegerField()),
                ('Date', models.TextField()),
                ('SumofPv', models.CharField(max_length=255)),
                ('RegionalManager', models.CharField(max_length=100)),
                ('ManagerName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TerritoryCollectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Executive', models.CharField(max_length=100)),
                ('Territory', models.CharField(max_length=200)),
                ('SalesEmployee', models.CharField(max_length=100)),
                ('TotalDues', models.IntegerField()),
                ('Balance', models.IntegerField()),
                ('Collected', models.IntegerField()),
                ('Collection', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=200)),
                ('agent_executive', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_executive_id', models.CharField(blank=True, max_length=100, null=True)),
                ('users_name', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phonenumber', models.CharField(max_length=10, validators=[App.models.validate_phonenumber])),
                ('user_location', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('superadmin', 'Super Admin'), ('executive', 'Executive'), ('agent', 'Agent'), ('DGIM', 'DGIM'), ('AGIM', 'AGIM'), ('manager', 'Manager'), ('LVD', 'LVD')], max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('userID', models.IntegerField(unique=True)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fcm_token', models.TextField(blank=True, null=True)),
                ('profile_image', models.ImageField(default='profile_image/default.jpg', upload_to='profile_image/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PlantEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_description', models.CharField(choices=[('Kumbalgodu(Bengaluru)', 'Kumbalgodu(Bengaluru)'), ('Kalaburagi(Gulbarga)', 'Kalaburagi(Gulbarga)'), ('Hosapete', 'Hosapete'), ('Dharwad(Hubballi)', 'Dharwad(Hubballi)'), ('Harihara(Davanagere)', 'Harihara(Davanagere)'), ('Mangaluru', 'Mangaluru'), ('Mysore', 'Mysore')], default='choose', max_length=50)),
                ('edition_description', models.CharField(choices=[('Bangalore city(BD)', 'BANGALORE CITY(BD)'), ('KOLAR/CHIKK/TUM(BD2)', 'KOLAR/CHIKK/TUM(BD2)'), ('Mysore city(YD)', 'MYSORE CITY(YD)'), ('Bangalore city edition(BP)', 'BANGALORE CITY EDITION(BP)'), ('Bangalore rural edition (BP1)', 'BANGALORE RURAL EDITION (BP1)'), ('Kolar dist edition(BP2)', 'KOLAR DIST EDITION'), ('Tumkur dist edition', 'TUMKUR DIST EDITION'), ('Mandya dist edition', 'MANDYA DIST EDITION'), ('chikkaballapur edition', 'CHIKKABALLAPUR EDITION'), ('ramanagara edition', 'RAMANAGARA EDITION')], default='choose', max_length=50)),
                ('date', models.DateField()),
                ('LPRtime', models.TimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentCollectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(max_length=50)),
                ('paymentmethod', models.CharField(choices=[('cheque', 'cheque'), ('cash', 'cash'), ('RTGS', 'RTGS'), ('NEFT', 'NEFT'), ('UPI', 'UPI')], max_length=50)),
                ('InstrumentNumber', models.IntegerField()),
                ('AmountCollected', models.IntegerField()),
                ('agent', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Executive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_location', models.TextField()),
                ('check_out_location', models.TextField(blank=True, null=True)),
                ('check_in_time', models.DateTimeField(max_length=200)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('total_time', models.CharField(blank=True, max_length=1000, null=True)),
                ('total_distance', models.CharField(blank=True, max_length=1000, null=True)),
                ('locations_visited', models.TextField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
