# Generated by Django 5.0.7 on 2024-08-05 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_working_summary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Market_worked', models.TextField()),
                ('Agents_visited', models.TextField()),
                ('Institution_visited', models.IntegerField(null=True)),
                ('Tasks_Accomplished', models.TextField(null=True)),
                ('Date', models.CharField(max_length=11)),
                ('Executive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
