# Generated by Django 5.0.7 on 2024-08-06 09:09

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_daily_working_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2024, 8, 6, 9, 9, 13, 623520, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
