# Generated by Django 5.0.7 on 2024-08-06 09:20

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_location_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='territorycollectionreport',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=datetime.datetime(2024, 8, 6, 9, 20, 47, 198443, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='Date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 8, 6, 9, 20, 47, 198443, tzinfo=datetime.timezone.utc)),
        ),
    ]
