# Generated by Django 5.0.7 on 2024-08-06 09:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_territorycollectionreport_date_alter_location_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplyreport',
            name='SumofDH',
            field=models.CharField(default=200, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='Date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 8, 6, 9, 22, 14, 724964, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='territorycollectionreport',
            name='Date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 8, 6, 9, 22, 14, 724964, tzinfo=datetime.timezone.utc)),
        ),
    ]
