# Generated by Django 5.0.7 on 2024-08-08 09:55

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_location_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='territorycollectionreport',
            name='Date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 8, 8, 9, 55, 54, 82606, tzinfo=datetime.timezone.utc)),
        ),
    ]
