# Generated by Django 5.0.7 on 2024-08-08 10:10

import App.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_location_check_in_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='Date',
            field=models.DateField(default=App.models.get_current_date),
        ),
        migrations.AlterField(
            model_name='territorycollectionreport',
            name='Date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 8, 8, 10, 10, 47, 128595, tzinfo=datetime.timezone.utc)),
        ),
    ]
