# Generated by Django 5.0.7 on 2024-08-09 05:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_alter_location_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territorycollectionreport',
            name='Date',
            field=models.DateField(verbose_name=datetime.datetime(2024, 8, 9, 5, 34, 25, 607873, tzinfo=datetime.timezone.utc)),
        ),
    ]
